version: '3.8'

services:
  nova-sonic-app:
    image: mrorbitman/jpc-sonic
    ports:
      - "3000:3000"  # WebSocket server
      - "8080:8080"  # Static frontend
    environment:
      - NODE_ENV=production
      # AWS credentials (uncomment and set as needed)
      # - AWS_PROFILE_NAME=${AWS_PROFILE_NAME}
      # - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      # - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      # - AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}
      # - AWS_REGION=${AWS_REGION:-us-east-1}
      # Custom system prompt
      # - SYSTEM_PROMPT=${SYSTEM_PROMPT}
      # CORS configuration
      - ALLOWED_ORIGINS=*
    restart: always

